services:
  - type: web
    name: finance-assistance
    env: docker
    dockerfilePath: ./Dockerfile
    buildContext: .
    branch: main
    port: 8501
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false