services:
  - type: web
    name: finance-assistance
    env: docker
    dockerfilePath: ./Dockerfile
    buildContext: .
    branch: main
    port: 8501  # Explicitly set the external port to 8501
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCP3AJBooBTEjAB79k4c9BKq5Nw3G8Vq4k
      - key: ALPHA_VANTAGE_API_KEY
        value: F7XF9BTX4NYZKE9O